server:
  port: 8090
  servlet:
    contextPath: /api
  
jasypt:
  encryptor:
    password: ${ASELLION_APP_ENCRYPTION_PASSWORD}

spring:  
  datasource:
    url: jdbc:postgresql://dev-legalfab.cxbmuufnozfa.ap-southeast-1.rds.amazonaws.com/dev_legalfab_db?user=dev_legalfab_admin&password=legalfab123&sslmode=require
    username: dev_legalfab_admin
    password: legalfab123    
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  path: logs
  
  file: ${logging.path}/asellion.log
