server:
  port: 8090
  servlet:
    contextPath: /api
  
jasypt:
  encryptor:
    password: ${ASELLION_APP_ENCRYPTION_PASSWORD}

spring:  
  datasource:
    url: ENC(5hcAhma/3LclcZA/uBpE1dD3/lErJTX7Ikb6oaJa9LHrtla5EUegRBzqHaygvbIK39d5wnS7kbzRflo3ySlx6latvbj+9Rw0++mvmFLHmGqQv3IXou+dUaIEsVm19uB0La09dO2+omacpvRLNCd3/CeSxAQN9t21RPAZtziBW77DvGMmB2Jeu5CQMXOKTd5KTSpX1nwVjKrNL0EWVNNBHMZT26NXgJBN3WLzLeTUkbKNZBen1Z6MWgnK/vvLE9jYddsf1AaIElo=)    
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  path: logs
  
  file: ${logging.path}/asellion.log
