server:
  port: 8090
  servlet:
    contextPath: /api
  
jasypt:
  encryptor:
    password: ${ASELLION_APP_ENCRYPTION_PASSWORD}

spring:  
  datasource:
    url: jdbc:postgresql://ec2-184-72-236-3.compute-1.amazonaws.com:5432/d82fpei3f3bn38?user=thefnbeyhlktal&password=58c47e5af4e0172fbdd5f628d10cad239f8690538e50789d640251c1faa596b0&sslmode=require
    username: thefnbeyhlktal
    password: 58c47e5af4e0172fbdd5f628d10cad239f8690538e50789d640251c1faa596b0    
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  path: logs
  
  file: ${logging.path}/asellion.log
